# Generated by Django 3.1 on 2021-01-13 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_tarefa_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
